# Generated by Django 4.2.16 on 2024-11-04 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tarefas", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tarefa",
            name="data_criacao",
        ),
        migrations.RemoveField(
            model_name="tarefa",
            name="descricao",
        ),
    ]
