# Generated by Django 4.2.16 on 2024-11-12 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tarefas", "0005_alter_atividade_idade"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Atividade",
        ),
        migrations.AlterModelOptions(
            name="tarefa",
            options={"ordering": ["-id"]},
        ),
    ]
